
spring:
  profiles:
    active:
    - dev
  application:
    name: BankCards
  datasource:
    url: jdbc:postgresql://localhost:5432/bankcards_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        "[format_sql]": true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  security:
    oauth2:
      client:
        registration:
          bankcards:
            client-id: bankcards
            client-authentication-method: none
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: 
              - openid
              - profile
              - email
              - read
        provider:
          bankcards:
            issuer-uri: ${OAUTH2_PROVIDER:http://auth-server:9000}
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_PROVIDER:http://auth-server:9000}
    # user:
      # name: user
      # password: "{noop}password"

#rsa keys
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

server:
  port: ${PORT:8080}
  servlet:
    session:
      cookie:
        name: BANK_CLIENT_SESSION

logging:
  level:
    "[com.example.bankcards]": DEBUG
    "[org.springframework.security]": TRACE
    liquibase: DEBUG
    "[org.springframework.web.client.RestTemplate]": DEBUG
    "[org.apache.hc.client5.http]": DEBUG
    "[org.springframework.security.oauth2.client]": DEBUG
    "[org.springframework.security.web.authentication]": DEBUG