
spring:
  profiles:
    active:
    - dev
  application:
    name: BankCards
  datasource:
    url: jdbc:postgresql://localhost:5432/bankcards_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        "[format_sql]": true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  security:
    oauth2:
      client:
        my-oauth-provider:
          authorization-uri: ${OAUTH2_PROVIDER:http://localhost:9000}/oauth2/authorize
          token-uri: ${OAUTH2_PROVIDER:http://localhost:9000}/oauth2/token
          user-info-uri: ${OAUTH2_PROVIDER:http://localhost:9000}/userinfo
          user-info-authentication-method: header
          jwk-set-uri: ${OAUTH2_PROVIDER:http://localhost:9000}/oauth2/jwks
          user-name-attribute: name
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_PROVIDER:http://localhost:9000}/issuer
    user:
      name: user
      password: p

#rsa keys
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

server:
  port: 8080

logging:
  level:
    "[com.example.bankcards]": DEBUG
    "[org.springframework.security]": DEBUG
    liquibase: DEBUG
