
spring:
  profiles:
    active:
    - dev
  application:
    name: BankRest
  datasource:
    url: jdbc:postgresql://localhost:5432/bankrest_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        "[format_sql]": true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  security:
    oauth2:
      client:
        registration:
          oidc-client:
            client-id: oidc-client
            client-authentication-method: none
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: 
              - openid
              - profile
              - email
              - read
        provider:
          oidc-client:
            issuer-uri: ${OAUTH2_PROVIDER:http://auth-server:9000}
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_PROVIDER:http://auth-server:9000}
  kafka:
    consumer:
      group-id: bankrest-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        "[spring.json.trusted.packages]": "com.example.common.*" # укажите ваш пакет с DTO
  docker:
    compose:
      file: ../compose.yaml 
      enabled: true

server:
  port: ${PORT:8080}
  servlet:
    session:
      cookie:
        name: BANK_CLIENT_SESSION

logging:
  level:
    "[com.example.bankrest]": DEBUG
    "[org.springframework.security]": DEBUG
    liquibase: DEBUG
    "[org.springframework.web.filter]": DEBUG
    # "[org.apache.hc.client5.http]": DEBUG
    "[org.springframework.security.oauth2.client]": TRACE
    "[org.springframework.security.web.authentication]": TRACE