
spring:
  application:
    name: BankCards
  datasource:
    url: jdbc:postgresql://localhost:5432/bankcards_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        "[format_sql]": true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  security:
    jwt:
      secret: mySecretKey123456789012345678901234567890
      expiration: 86400000 # 24 hours

server:
  port: 8080

logging:
  level:
    "[com.example.bankcards]": DEBUG
    "[org.springframework.security]": DEBUG
    liquibase: DEBUG

springdoc:
  swagger-ui.path: /swagger-ui.html
  api-docs.path: /v3/api-docs
