
spring:
  application:
    name: AuthorizationServer
  security:
    oauth2:
      authorizationserver:
        client:
          oidc-client:
            registration:
              client-id: "oidc-client"
              client-name: "oidc-client"
              client-authentication-methods:
                - "none"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "http://client-app:8080/login/oauth2/code/oidc-client"
              post-logout-redirect-uris:
                - "http://127.0.0.1:8080/"
              scopes:
                - "openid"
                - "profile"
                - "email"
                - "read"
            # require-authorization-consent: true
       
server:
  port: ${PORT:9000}
  servlet:
    session:
      tracking-modes: cookie
      cookie:
        name: AUTH_SERVER_SESSIONID

logging:
  level:
    "[com.example.authorizationserver]": DEBUG
    # "[org.springframework.security]": DEBUG
    
    # org.springframework.security.oauth2.server.authorization: TRACE
    # org.springframework.security.oauth2: DEBUG
    # org.springframework.web: DEBUG
    # org.hibernate.SQL: DEBUG