services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=authorization_db'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=password'
    ports:
      - '5432'
