
spring:
  application:
    name: AuthorizationServer
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/authorization_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        "[format_sql]": true
  liquibase:
    change-log: classpath:db/migration/root.yaml
    enabled: true
  security:
    oauth2:
      authorizationserver:
        client:
          oidc-client:
            registration:
              client-id: "oidc-client"
              client-name: "oidc-client"
              client-authentication-methods:
                - "none"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - ${CLIENT_APP_LOGIN_REDIRECT_URL:http://client-app:8080/login/oauth2/code/oidc-client}
              post-logout-redirect-uris:
                - ${CLIENT_APP_LOGOUT_REDIRECT_URL:http://client-app:8080/login?logout}
              scopes:
                - "openid"
                - "profile"
                - "email"
                - "read"
            require-authorization-consent: false
  kafka:
    bootstrap-servers: 
      - ${KAFKA_SERVER:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer      
  docker:
    compose:
      file: ../compose.yaml 
      enabled: true
      readiness:
        wait: always # Ожидать готовности контейнеров перед запуском приложения
        timeout: 2m
server:
  port: ${PORT:9000}
  servlet:
    session:
      tracking-modes: cookie
      cookie:
        name: AUTHORIZATION_SERVER_SESSIONID

logging:
  level:
    "[com.example.authorizationserver]": DEBUG
    liquibase: DEBUG
    "[org.springframework.security]": DEBUG
    
    # org.springframework.security.oauth2.server.authorization: TRACE
    # org.springframework.security.oauth2: DEBUG
    # org.springframework.web: DEBUG
    # org.hibernate.SQL: DEBUG