
spring:
  application:
    name: AuthorizationServer
       
server:
  port: ${PORT:9000}
  servlet:
    session:
      tracking-modes: cookie

logging:
  level:
    "[com.example.authorizationserver]": DEBUG
    "[org.springframework.security]": DEBUG

app:
  node-name: ${HOSTNAME:localhost.ru.test}  # Uses OS HOSTNAME env var, defaults to localhost
